import React, { useEffect } from 'react'
import { CircleMarker, MapContainer, Polyline, TileLayer, Tooltip, useMap } from 'react-leaflet'

function Follow({ point }) { const map = useMap(); useEffect(() => { if (point) map.setView([point.latitude, point.longitude], Math.max(map.getZoom(), 15), { animate: true }) }, [point, map]); return null }
function Focus({ point }) { const map = useMap(); useEffect(() => { if (point) map.flyTo([point.latitude, point.longitude], Math.max(map.getZoom(), 15), { duration: .6 }) }, [point, map]); return null }
export default function MapViewer({ detections = [], selected, onSelect, location, scanLocation, track = [], demo = true }) {
  const inferredScanLocation = scanLocation || detections.find(d => Number.isFinite(d.latitude) && Number.isFinite(d.longitude))
  const center = inferredScanLocation ? [inferredScanLocation.latitude, inferredScanLocation.longitude] : location ? [location.latitude, location.longitude] : [18.5204, 73.8567]
  const points = track.length > 1 ? track : []
  return <MapContainer center={center} zoom={14} className="map" aria-label="Survey map"><TileLayer attribution="&copy; OpenStreetMap contributors" url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png" />{points.length > 1 && <Polyline positions={points} pathOptions={{ color: '#39b9d1', weight: 3 }} />}{location && <CircleMarker center={[location.latitude, location.longitude]} radius={8} pathOptions={{ color: '#b9f4ff', fillColor: '#167f98', fillOpacity: 1 }}><Tooltip permanent>Current GPS position</Tooltip></CircleMarker>}{inferredScanLocation && <CircleMarker center={[inferredScanLocation.latitude, inferredScanLocation.longitude]} radius={9} pathOptions={{ color: '#f3c969', fillColor: '#b58a20', fillOpacity: 1 }}><Tooltip permanent>Scan location</Tooltip></CircleMarker>}{detections.filter(d => Number.isFinite(d.latitude) && Number.isFinite(d.longitude)).map(d => <CircleMarker key={d.id} center={[d.latitude, d.longitude]} radius={selected?.id === d.id ? 11 : 7} pathOptions={{ color: d.severity === 'high' ? '#ff8d70' : '#f3c969', fillColor: d.severity === 'high' ? '#cf4d37' : '#b58a20', fillOpacity: 1 }} eventHandlers={{ click: () => onSelect(d) }}><Tooltip>{d.id} · {Math.round(d.confidence * 100)}%</Tooltip></CircleMarker>)}<Follow point={inferredScanLocation || location} /><Focus point={selected?.latitude ? selected : null} /></MapContainer>
}
